ETCM-730 Proof read OBFT documentation
input-output-hk/OBFT-Checkpointing-Specification pull request #1
Opened 2021-04-08 03:54 UTC by NeilBurgess42

Please ensure I have not changed any meaning.

2021-04-08 11:55 UTC, Infinisil requested changes

2021-04-08 11:55 UTC, Infinisil commented on formal-spec/obft.tex
> +Upon receiving the NEWVOTE signal (fig. \ref{fig:checkpoint-consensus-rules}), which is a transaction carrying a \var{vote}, the voting process begins. If the \var{vote} has a correct signature, then
The voting process is continuously in progress, so it's not that it begins with a `NEWVOTE` signal. It's more that this signal just adds another vote. I think maybe this should be something like

> Upon receiving the NEWVOTE signal, which is a transaction carrying a \var{vote}, the consensus rules (fig. \ref{fig:checkpoint-consensus-rules}) determine how the node state changes as a result.

2021-04-09 01:00 UTC, NeilBurgess42 commented on formal-spec/obft.tex
> +Upon receiving the NEWVOTE signal (fig. \ref{fig:checkpoint-consensus-rules}), which is a transaction carrying a \var{vote}, the voting process begins. If the \var{vote} has a correct signature, then
Accepted your change, thank you.

2021-04-09 12:09 UTC, Infinisil approved these changes

2021-04-09 12:09 UTC, merged